version: '2.4'

services:
  app:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./ngin:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5432:5432"
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -h localhost -d user && psql -U user -h localhost -d user -c 'SELECT 1'" ]
      interval: 5s
      timeout: 5s
      retries: 10
